import { Inject, Injectable } from '@nestjs/common';
import { CreateRoadmapCommand } from '../commands/create-roadmap.command';
import { UpdateRoadmapCommand } from '../commands/update-roadmap.command';
import { DeleteRoadmapCommand } from '../commands/delete-roadmap.command';
import { ROADMAP_REPOSITORY } from '../ports/roadmap.repository';
import type { RoadmapRepository } from '../ports/roadmap.repository';
import { GetRoadmapBySlugQuery } from '../queries/get-roadmap-by-slug.query';
import { ListRoadmapsQuery } from '../queries/list-roadmaps.query';
import { GetSkillNodesQuery } from '../queries/get-skill-nodes.query';
import {
  RoadmapEntity,
  RoadmapPageEntity,
} from '../../domain/entities/roadmap.entity';
import { NodeEntity } from '../../domain/entities/node.entity';
import {
  RoadmapValidationDomainError,
  RoadmapNotFoundDomainError,
} from '../../domain/errors/roadmap-domain-error';
import {
  validateCreateRoadmapInput,
  validateUpdateRoadmapInput,
  validateRoadmapSlug,
} from '../../domain/policies/roadmap-input.policy';

/**
 * Application service for roadmap operations
 * Orchestrates commands and queries using repositories
 * Implements use cases: create, update, delete, retrieve roadmaps
 */
@Injectable()
export class RoadmapApplicationService {
  constructor(
    @Inject(ROADMAP_REPOSITORY)
    private readonly roadmapRepository: RoadmapRepository,
  ) {}

  /**
   * Lists roadmaps with filtering and pagination
   * @param query - List query with optional category filter and pagination
   * @returns Paginated roadmap results
   */
  async listRoadmaps(query: ListRoadmapsQuery): Promise<RoadmapPageEntity> {
    const limit = query.limit ?? 24;
    if (!Number.isInteger(limit) || limit < 1 || limit > 100) {
      throw new RoadmapValidationDomainError(
        'Limit must be an integer between 1 and 100.',
        'listRoadmaps',
      );
    }

    const cursor = query.cursor ?? null;
    if (cursor !== null && cursor.trim().length === 0) {
      throw new RoadmapValidationDomainError(
        'Cursor must not be an empty string.',
        'listRoadmaps',
      );
    }

    const isAdmin = query.isAdmin ?? false;

    return this.roadmapRepository.list(
      {
        category: query.category,
      },
      {
        limit,
        cursor,
      },
      isAdmin,
    );
  }

  /**
   * Retrieves a roadmap by slug
   * @param query - Query with slug
   * @returns Roadmap entity or null if not found
   */
  async getRoadmapBySlug(
    query: GetRoadmapBySlugQuery,
  ): Promise<RoadmapEntity | null> {
    const normalizedSlug = query.slug.trim();
    if (normalizedSlug.length === 0) {
      throw new RoadmapValidationDomainError(
        'Slug must not be empty.',
        'getRoadmapBySlug',
      );
    }

    validateRoadmapSlug(normalizedSlug, 'getRoadmapBySlug');
    return this.roadmapRepository.findBySlug(normalizedSlug);
  }

  /**
   * Creates a new roadmap
   * @param command - Create roadmap command with all required fields
   * @returns Created roadmap entity
   */
  async createRoadmap(command: CreateRoadmapCommand): Promise<RoadmapEntity> {
    const normalizedCommand: CreateRoadmapCommand = {
      ...command,
      slug: command.slug.trim(),
      title: command.title.trim(),
      description: command.description.trim(),
    };

    validateCreateRoadmapInput(normalizedCommand);

    // Create roadmap entity without ID (will be generated by repository)
    const roadmapToCreate: Omit<RoadmapEntity, 'id'> = {
      slug: normalizedCommand.slug,
      title: normalizedCommand.title,
      description: normalizedCommand.description,
      category: normalizedCommand.category,
      difficulty: normalizedCommand.difficulty,
      nodesJson: normalizedCommand.nodesJson,
      edgesJson: normalizedCommand.edgesJson,
      topicCount: normalizedCommand.topicCount,
      status: normalizedCommand.status,
      createdAt: Date.now(),
    };

    return this.roadmapRepository.create(roadmapToCreate);
  }

  /**
   * Updates an existing roadmap
   * @param command - Update roadmap command with ID and fields to update
   * @returns Updated roadmap entity
   */
  async updateRoadmap(command: UpdateRoadmapCommand): Promise<RoadmapEntity> {
    // Validate ID
    if (!command.id || command.id.trim().length === 0) {
      throw new RoadmapValidationDomainError(
        'Roadmap ID is required.',
        'updateRoadmap',
      );
    }

    // Check if roadmap exists
    const existing = await this.roadmapRepository.findById(command.id);
    if (!existing) {
      throw new RoadmapNotFoundDomainError(
        `Roadmap with id '${command.id}' not found.`,
        'updateRoadmap',
      );
    }

    // Normalize string fields if provided
    const normalizedCommand: UpdateRoadmapCommand = {
      ...command,
      slug: command.slug?.trim(),
      title: command.title?.trim(),
      description: command.description?.trim(),
    };

    // Validate update input
    validateUpdateRoadmapInput(normalizedCommand);

    // Build update object (exclude id and undefined values)
    const { id, ...updates } = normalizedCommand;
    const updateData: Partial<Omit<RoadmapEntity, 'id'>> = {};

    if (updates.slug !== undefined) updateData.slug = updates.slug;
    if (updates.title !== undefined) updateData.title = updates.title;
    if (updates.description !== undefined)
      updateData.description = updates.description;
    if (updates.category !== undefined) updateData.category = updates.category;
    if (updates.difficulty !== undefined)
      updateData.difficulty = updates.difficulty;
    if (updates.nodesJson !== undefined)
      updateData.nodesJson = updates.nodesJson;
    if (updates.edgesJson !== undefined)
      updateData.edgesJson = updates.edgesJson;
    if (updates.topicCount !== undefined)
      updateData.topicCount = updates.topicCount;
    if (updates.status !== undefined) updateData.status = updates.status;

    return this.roadmapRepository.update(id, updateData);
  }

  /**
   * Deletes a roadmap by ID
   * @param command - Delete roadmap command with ID
   */
  async deleteRoadmap(command: DeleteRoadmapCommand): Promise<void> {
    // Validate ID
    if (!command.id || command.id.trim().length === 0) {
      throw new RoadmapValidationDomainError(
        'Roadmap ID is required.',
        'deleteRoadmap',
      );
    }

    // Check if roadmap exists
    const existing = await this.roadmapRepository.findById(command.id);
    if (!existing) {
      throw new RoadmapNotFoundDomainError(
        `Roadmap with id '${command.id}' not found.`,
        'deleteRoadmap',
      );
    }

    await this.roadmapRepository.delete(command.id);
  }

  /**
   * Retrieves skill nodes for role roadmap editing
   * Fetches all nodes from skill roadmaps for drag-and-drop reuse
   * @param query - Query with optional isAdmin flag
   * @returns Array of node entities from skill roadmaps
   */
  async getSkillNodesForRoleRoadmap(
    query: GetSkillNodesQuery,
  ): Promise<NodeEntity[]> {
    const isAdmin = query.isAdmin ?? false;

    // Fetch all skill roadmaps
    const skillRoadmaps =
      await this.roadmapRepository.findSkillRoadmaps(isAdmin);

    // Extract and parse nodes from all skill roadmaps
    const allNodes: NodeEntity[] = [];

    for (const roadmap of skillRoadmaps) {
      try {
        const nodes = JSON.parse(roadmap.nodesJson) as NodeEntity[];

        // Add metadata to indicate these are from skill roadmaps
        const nodesWithMetadata = nodes.map((node) => ({
          ...node,
          data: {
            ...node.data,
            originalRoadmapId: roadmap.id,
          },
        }));

        allNodes.push(...nodesWithMetadata);
      } catch (error) {
        // Skip roadmaps with invalid JSON (should not happen with validation)
        console.error(
          `Failed to parse nodesJson for roadmap ${roadmap.id}:`,
          error,
        );
      }
    }

    return allNodes;
  }
}
