import { ObjectType, Field, ID } from '@nestjs/graphql';

/**
 * GraphQL object type for Roadmap entity
 *
 * This schema defines the GraphQL representation of a roadmap that will be
 * exposed through the GraphQL API. It maps to the Roadmap domain model and
 * is used in queries and mutations.
 *
 * All fields are decorated with @Field to make them available in the GraphQL schema.
 * The ID type is used for the unique identifier to follow GraphQL best practices.
 */
@ObjectType()
export class RoadmapSchema {
  /**
   * Unique identifier generated by Convex
   * Exposed as GraphQL ID type for proper client-side caching
   */
  @Field(() => ID)
  id!: string;

  /**
   * URL-friendly identifier for the roadmap
   * Used for human-readable URLs and lookups
   */
  @Field()
  slug!: string;

  /**
   * Display title of the roadmap
   * Main heading shown to users
   */
  @Field()
  title!: string;

  /**
   * Short description of the roadmap
   * Summary text for previews and listings
   */
  @Field()
  description!: string;

  /**
   * Full markdown content of the roadmap
   * Complete roadmap content in markdown format
   */
  @Field()
  content!: string;

  /**
   * Clerk user ID of the roadmap creator
   * References the user who created this roadmap
   */
  @Field()
  author!: string;

  /**
   * Category tags for organizing roadmaps
   * Array of strings for categorization and filtering
   */
  @Field(() => [String])
  tags!: string[];

  /**
   * Unix timestamp when the roadmap was published
   * Milliseconds since epoch
   */
  @Field()
  publishedAt!: number;

  /**
   * Unix timestamp when the roadmap was last updated
   * Milliseconds since epoch, automatically updated on changes
   */
  @Field()
  updatedAt!: number;

  /**
   * Publication status flag
   * Determines if the roadmap is visible to public users
   */
  @Field()
  isPublished!: boolean;
}
