/**
 * Domain model interfaces for Roadmap entity
 *
 * These interfaces define the core domain models used throughout the roadmap module.
 * They represent the business entities and their data transfer objects (DTOs).
 */

/**
 * Roadmap entity representing a technology roadmap
 *
 * This interface maps to the roadmap table in Convex database.
 * All fields are required and represent the complete state of a roadmap.
 */
export interface Roadmap {
  /** Unique identifier generated by Convex */
  _id: string;

  /** URL-friendly identifier for the roadmap */
  slug: string;

  /** Display title of the roadmap */
  title: string;

  /** Short description of the roadmap */
  description: string;

  /** Full markdown content of the roadmap */
  content: string;

  /** Clerk user ID of the roadmap creator */
  author: string;

  /** Category tags for organizing roadmaps */
  tags: string[];

  /** Unix timestamp when the roadmap was published */
  publishedAt: number;

  /** Unix timestamp when the roadmap was last updated */
  updatedAt: number;

  /** Publication status flag */
  isPublished: boolean;
}

/**
 * Input data for creating a new roadmap
 *
 * This interface defines the required fields when creating a roadmap.
 * The author field is not included as it's extracted from the authenticated user context.
 * Timestamps (_id, publishedAt, updatedAt) are auto-generated by the system.
 */
export interface CreateRoadmapInput {
  /** URL-friendly identifier for the roadmap (must be unique) */
  slug: string;

  /** Display title of the roadmap */
  title: string;

  /** Short description of the roadmap */
  description: string;

  /** Full markdown content of the roadmap */
  content: string;

  /** Category tags for organizing roadmaps */
  tags: string[];

  /** Publication status flag */
  isPublished: boolean;
}

/**
 * Input data for updating an existing roadmap
 *
 * This interface defines the fields that can be updated on a roadmap.
 * All fields except 'id' are optional, allowing partial updates.
 * The updatedAt timestamp is automatically updated by the system.
 */
export interface UpdateRoadmapInput {
  /** Unique identifier of the roadmap to update */
  id: string;

  /** URL-friendly identifier for the roadmap (must be unique if changed) */
  slug?: string;

  /** Display title of the roadmap */
  title?: string;

  /** Short description of the roadmap */
  description?: string;

  /** Full markdown content of the roadmap */
  content?: string;

  /** Category tags for organizing roadmaps */
  tags?: string[];

  /** Publication status flag */
  isPublished?: boolean;
}
