// This file exports all generated types and schemas
// Generated by GraphQL Code Generator

// TypeScript types from GraphQL schema
export * from './types';

// Zod validation schemas for runtime validation
export {
  // Enum schemas
  ResourceTypeSchema,
  ProgressStatusSchema,
  RoadmapStatusSchema,
  RoadmapDifficultySchema,
  RoadmapCategorySchema,

  // Input schemas
  UpdateProgressInputSchema,
  PaginationInputSchema,
  PositionInputSchema,
  NodeDataInputSchema,
  ResourceInputSchema,
  CreateTopicInputSchema,
  NodeInputSchema,
  EdgeInputSchema,
  UpdateRoadmapInputSchema,
  RoadmapFiltersSchema,
  CreateRoadmapInputSchema,
} from './zod-schemas';

// Note: operations.ts and hooks.ts will be generated
// when you add GraphQL queries/mutations to your code
// Uncomment these lines after adding operations:
// export * from './operations';
// export * from './hooks';
