// This file exports all generated types and schemas
// Generated by GraphQL Code Generator

// TypeScript types from GraphQL schema
export * from './types';

// Zod validation schemas for runtime validation
// Note: Only exporting schemas that exist in zod-schemas.ts
export {
  RoadmapCategorySchema,
  RoadmapDifficultySchema,
  RoadmapStatusSchema,
  RoadmapPageInputSchema,
  CreateRoadmapInputSchema,
} from './zod-schemas';

// Note: operations.ts and hooks.ts will be generated
// when you add GraphQL queries/mutations to your code
// Uncomment these lines after adding operations:
// export * from './operations';
// export * from './hooks';
