import { ObjectType, Field, ID, Int } from '@nestjs/graphql';

/**
 * GraphQL object type for Article entity
 *
 * This schema defines the GraphQL representation of an article that will be
 * exposed through the GraphQL API. It maps to the Article domain model and
 * is used in queries and mutations.
 *
 * All fields are decorated with @Field to make them available in the GraphQL schema.
 * The ID type is used for the unique identifier to follow GraphQL best practices.
 *
 * Requirements: 2.1, 2.6, 2.7, 2.10, 9.1
 */
@ObjectType('Article')
export class ArticleSchema {
  /**
   * Unique identifier generated by Convex
   * Exposed as GraphQL ID type for proper client-side caching
   */
  @Field(() => ID)
  id!: string;

  /**
   * URL-friendly identifier for the article
   * Used for human-readable URLs and lookups
   */
  @Field()
  slug!: string;

  /**
   * Display title of the article
   * Main heading shown to users
   */
  @Field()
  title!: string;

  /**
   * Full rich-text content of the article
   * Complete article content in HTML/JSON format from Tiptap editor
   */
  @Field()
  content!: string;

  /**
   * Clerk user ID of the article creator
   * References the user who created this article
   */
  @Field()
  author!: string;

  /**
   * Category tags for organizing articles
   * Array of strings for categorization and filtering
   */
  @Field(() => [String])
  tags!: string[];

  /**
   * Unix timestamp when the article was created
   * Milliseconds since epoch
   */
  @Field()
  createdAt!: number;

  /**
   * Unix timestamp when the article was last updated
   * Milliseconds since epoch, automatically updated on changes
   */
  @Field()
  updatedAt!: number;

  /**
   * Publication status flag
   * Determines if the article is visible to public users
   */
  @Field()
  isPublished!: boolean;

  /**
   * Soft delete flag
   * Marks article as deleted without removing from database
   */
  @Field()
  isDeleted!: boolean;

  /**
   * Estimated reading time in minutes
   * Calculated based on word count (200 words/minute)
   */
  @Field(() => Int)
  readingTime!: number;

  /**
   * Total word count of the article
   * Calculated from content (excluding HTML tags)
   */
  @Field(() => Int)
  wordCount!: number;
}
